name: Construir y Publicar Imagen Docker

on:
  push:
    branches:
      - 'master'
      - 'dev'
      - 'release/*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesión en el registro de contenedores
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar etiquetas Docker
        id: docker_tag
        run: |
          if [[ ${{ github.ref }} == refs/heads/master ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref }} == refs/heads/dev ]]; then
            echo "tag=beta" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref }} == refs/heads/release/* ]]; then
            VERSION=$(echo ${{ github.ref }} | sed 's/refs\/heads\/release\/v*//')
            echo "tag=$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Construir y publicar imagen Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.docker_tag.outputs.tag }}
